version: "3.8"
services:

    # db:
    #     image: mysql
    #     container_name: db_docker_symfony
    #     restart: always
    #     volumes:
    #         - ./var/lib/mysql
    #     environment:
    #         MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #     networks:
    #         - dev

    # phpmyadmin:
    #     image: phpmyadmin
    #     container_name: phpmyadmin_docker_symfony
    #     restart: always
    #     depends_on:
    #         - db
    #     ports:
    #         - 8080:80
    #     environment:
    #         PMA_HOST: db
    #     networks:
    #         - dev

    mongo:
        image: mongo:4.0.6
        container_name: mongodb_docker_symfony
        volumes:
          - './var/data:/data/db'
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin_recipients

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: admin
          ME_CONFIG_MONGODB_ADMINPASSWORD: admin_recipients


    maildev:
        image: maildev/maildev
        container_name: maildev_docker_symfony
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_docker_symfony
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev



networks:
    dev:

volumes:
    db-data:


